/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kk
 */
public class hungman extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public hungman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rof = new javax.swing.JLabel();
        manm = new javax.swing.JLabel();
        poll = new javax.swing.JLabel();
        tabil2 = new javax.swing.JLabel();
        tabil = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        ans1 = new javax.swing.JTextField();
        q2 = new javax.swing.JLabel();
        ans2 = new javax.swing.JTextField();
        q3 = new javax.swing.JLabel();
        ans3 = new javax.swing.JTextField();
        q4 = new javax.swing.JLabel();
        ans4 = new javax.swing.JTextField();
        q5 = new javax.swing.JLabel();
        ans5 = new javax.swing.JTextField();
        sub5 = new javax.swing.JButton();
        sub1 = new javax.swing.JButton();
        sub2 = new javax.swing.JButton();
        sub3 = new javax.swing.JButton();
        sub4 = new javax.swing.JButton();
        right1 = new javax.swing.JLabel();
        wrong1 = new javax.swing.JLabel();
        right2 = new javax.swing.JLabel();
        wrong2 = new javax.swing.JLabel();
        right3 = new javax.swing.JLabel();
        wrong3 = new javax.swing.JLabel();
        right4 = new javax.swing.JLabel();
        wrong4 = new javax.swing.JLabel();
        right5 = new javax.swing.JLabel();
        wrong5 = new javax.swing.JLabel();
        gmo = new javax.swing.JLabel();
        win = new javax.swing.JLabel();
        gmo1 = new javax.swing.JLabel();
        run = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1011, 590));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        rof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s6.png"))); // NOI18N
        rof.setText("jLabel1");
        getContentPane().add(rof);
        rof.setBounds(650, 70, 30, 80);

        manm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s5.png"))); // NOI18N
        manm.setText("jLabel1");
        getContentPane().add(manm);
        manm.setBounds(600, 20, 130, 550);

        poll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s2.png"))); // NOI18N
        poll.setText("jLabel3");
        getContentPane().add(poll);
        poll.setBounds(640, 0, 140, 550);

        tabil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s4.png"))); // NOI18N
        getContentPane().add(tabil2);
        tabil2.setBounds(640, 440, 70, 70);

        tabil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s3.png"))); // NOI18N
        tabil.setText("jLabel2");
        getContentPane().add(tabil);
        tabil.setBounds(390, 480, 440, 80);

        q1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q1.setText("Q1. What is the currency name of Bangladesh?");
        getContentPane().add(q1);
        q1.setBounds(60, 110, 430, 22);

        ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1ActionPerformed(evt);
            }
        });
        getContentPane().add(ans1);
        ans1.setBounds(90, 140, 180, 30);

        q2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q2.setText("Q2. What is the currency name of India?");
        getContentPane().add(q2);
        q2.setBounds(70, 170, 430, 30);

        ans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans2ActionPerformed(evt);
            }
        });
        getContentPane().add(ans2);
        ans2.setBounds(90, 200, 180, 30);

        q3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q3.setText("Q3. What is the currency name of Iran ?");
        getContentPane().add(q3);
        q3.setBounds(70, 240, 430, 20);

        ans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans3ActionPerformed(evt);
            }
        });
        getContentPane().add(ans3);
        ans3.setBounds(90, 270, 180, 30);

        q4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q4.setText("Q4. What is the currency name of Kuwait?");
        getContentPane().add(q4);
        q4.setBounds(80, 310, 440, 22);
        getContentPane().add(ans4);
        ans4.setBounds(90, 340, 180, 30);

        q5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        q5.setText("Q5. What is the currency name of Jordan?");
        getContentPane().add(q5);
        q5.setBounds(80, 390, 430, 22);

        ans5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans5ActionPerformed(evt);
            }
        });
        getContentPane().add(ans5);
        ans5.setBounds(90, 420, 170, 30);

        sub5.setText("Submit");
        sub5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub5MouseClicked(evt);
            }
        });
        sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub5ActionPerformed(evt);
            }
        });
        getContentPane().add(sub5);
        sub5.setBounds(270, 420, 90, 30);

        sub1.setText("Submit");
        sub1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub1MouseClicked(evt);
            }
        });
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        getContentPane().add(sub1);
        sub1.setBounds(280, 140, 65, 23);

        sub2.setText("Submit");
        sub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub2MouseClicked(evt);
            }
        });
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });
        getContentPane().add(sub2);
        sub2.setBounds(290, 200, 65, 23);

        sub3.setText("Submit");
        sub3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub3MouseClicked(evt);
            }
        });
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });
        getContentPane().add(sub3);
        sub3.setBounds(290, 270, 65, 23);

        sub4.setText("Submit");
        sub4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub4MouseClicked(evt);
            }
        });
        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });
        getContentPane().add(sub4);
        sub4.setBounds(290, 340, 65, 23);

        right1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        getContentPane().add(right1);
        right1.setBounds(280, 140, 30, 30);

        wrong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        wrong1.setText("jLabel2");
        getContentPane().add(wrong1);
        wrong1.setBounds(280, 140, 30, 30);

        right2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        getContentPane().add(right2);
        right2.setBounds(280, 200, 30, 20);

        wrong2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        wrong2.setText("jLabel4");
        getContentPane().add(wrong2);
        wrong2.setBounds(280, 200, 30, 20);

        right3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        getContentPane().add(right3);
        right3.setBounds(280, 270, 30, 30);

        wrong3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(wrong3);
        wrong3.setBounds(280, 270, 30, 30);

        right4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        getContentPane().add(right4);
        right4.setBounds(280, 340, 30, 30);

        wrong4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(wrong4);
        wrong4.setBounds(280, 340, 30, 30);

        right5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        getContentPane().add(right5);
        right5.setBounds(270, 420, 40, 30);

        wrong5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(wrong5);
        wrong5.setBounds(270, 420, 30, 30);

        gmo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gmo.setForeground(new java.awt.Color(0, 204, 51));
        gmo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmo.setText("Game Over");
        getContentPane().add(gmo);
        gmo.setBounds(390, 140, 180, 30);

        win.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        win.setForeground(new java.awt.Color(0, 153, 51));
        win.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        win.setText("YOU WIN");
        getContentPane().add(win);
        win.setBounds(400, 160, 160, 50);

        gmo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gmo1.setForeground(new java.awt.Color(255, 0, 51));
        gmo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gmo1.setText("Game Over");
        getContentPane().add(gmo1);
        gmo1.setBounds(400, 130, 170, 40);

        run.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        run.setForeground(new java.awt.Color(255, 0, 0));
        run.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        run.setText("You Death");
        getContentPane().add(run);
        run.setBounds(420, 160, 120, 50);

        man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/22222222.png"))); // NOI18N
        getContentPane().add(man);
        man.setBounds(620, 110, 100, 320);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1010, 555);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans1ActionPerformed

    private void ans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        tabil2.setVisible(false);
        manm.setVisible(false);
        rof.setVisible(false);
        q2.setVisible(false);
        q3.setVisible(false);
        q4.setVisible(false);
        q5.setVisible(false);
        ans2.setVisible(false);
        ans3.setVisible(false);
        ans4.setVisible(false);
        ans5.setVisible(false);
        poll.setVisible(false);
        right1.setVisible(false);
        right2.setVisible(false);
        right3.setVisible(false);
        right4.setVisible(false);
        right5.setVisible(false);
        wrong1.setVisible(false);
        wrong2.setVisible(false);
        wrong3.setVisible(false);
        wrong4.setVisible(false);
        wrong5.setVisible(false);
        sub2.setVisible(false);
        sub3.setVisible(false);
        sub4.setVisible(false);
        sub5.setVisible(false);
        gmo1.setVisible(false);
            run.setVisible(false);
            gmo.setVisible(false);
            win.setVisible(false);
            man.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void ans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans2ActionPerformed

    private void ans5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans5ActionPerformed

    private void sub5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub5MouseClicked
       
    }//GEN-LAST:event_sub5MouseClicked

    private void sub1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1MouseClicked

    private void sub2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2MouseClicked

    private void sub3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3MouseClicked

    private void sub4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4MouseClicked

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
         
        String a = "Taka";
        if(ans1.getText().compareToIgnoreCase(a) == 0){
            right1.setVisible(true);
            ans2.setVisible(true);
            sub1.setVisible(false);
            sub2.setVisible(true);
            q2.setVisible(true);
        }
        else{
           wrong1.setVisible(true);
           q2.setVisible(true);
           ans2.setVisible(true);
           sub2.setVisible(true);
           sub1.setVisible(false);
           poll.setVisible(true);
        }
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
         
        String b = "Rupee";
        if(ans2.getText().compareToIgnoreCase(b) == 0){
            right2.setVisible(true);
            q3.setVisible(true);
            ans3.setVisible(true);
            sub2.setVisible(false);
            sub3.setVisible(true);
            
        }
        else{
           wrong2.setVisible(true);
           q3.setVisible(true);
           ans3.setVisible(true);
           sub3.setVisible(true);
           sub2.setVisible(false);
           poll.setVisible(true);
           rof.setVisible(true);
        }
    }//GEN-LAST:event_sub2ActionPerformed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
         
        String c = "Rial";
        if(ans3.getText().compareToIgnoreCase(c) == 0){
           right3.setVisible(true);
            q4.setVisible(true);
            ans4.setVisible(true);
            sub3.setVisible(false);
            sub4.setVisible(true);
        }
        else{
            wrong3.setVisible(true);
           q4.setVisible(true);
           ans4.setVisible(true);
           sub4.setVisible(true);
           sub3.setVisible(false);
           poll.setVisible(true);
           rof.setVisible(true);
           tabil2.setVisible(true);
        }
    }//GEN-LAST:event_sub3ActionPerformed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        
        String d = "Diner";
        if(ans4.getText().compareToIgnoreCase(d) == 0){
            right4.setVisible(true);
            q5.setVisible(true);
            ans5.setVisible(true);
            sub4.setVisible(false);
            sub5.setVisible(true);
        }
        else{
             wrong4.setVisible(true);
           q5.setVisible(true);
           ans5.setVisible(true);
           sub5.setVisible(true);
           sub4.setVisible(false);
           poll.setVisible(true);
           rof.setVisible(true);
           tabil2.setVisible(true);
           manm.setVisible(true);
        }
    }//GEN-LAST:event_sub4ActionPerformed

    private void sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub5ActionPerformed
        
        String e = "Dollar";
        if(ans5.getText().compareToIgnoreCase(e) == 0){
            right5.setVisible(true);
            poll.setVisible(false);
            tabil2.setVisible(false);
            tabil.setVisible(false);
            sub5.setVisible(false);
            gmo.setVisible(true);
            win.setVisible(true);
            rof.setVisible(false);
             manm.setVisible(false);
            
        }
        else{
          wrong5.setVisible(true);
            poll.setVisible(true);
            tabil2.setVisible(false);
            tabil.setVisible(true);
            sub5.setVisible(false);
            man.setVisible(true);
            gmo1.setVisible(true);
            run.setVisible(true);
            manm.setVisible(false);
        }
    }//GEN-LAST:event_sub5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hungman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hungman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hungman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hungman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hungman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans1;
    private javax.swing.JTextField ans2;
    private javax.swing.JTextField ans3;
    private javax.swing.JTextField ans4;
    private javax.swing.JTextField ans5;
    private javax.swing.JLabel background;
    private javax.swing.JLabel gmo;
    private javax.swing.JLabel gmo1;
    private javax.swing.JLabel man;
    private javax.swing.JLabel manm;
    private javax.swing.JLabel poll;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel right1;
    private javax.swing.JLabel right2;
    private javax.swing.JLabel right3;
    private javax.swing.JLabel right4;
    private javax.swing.JLabel right5;
    private javax.swing.JLabel rof;
    private javax.swing.JLabel run;
    private javax.swing.JButton sub1;
    private javax.swing.JButton sub2;
    private javax.swing.JButton sub3;
    private javax.swing.JButton sub4;
    private javax.swing.JButton sub5;
    private javax.swing.JLabel tabil;
    private javax.swing.JLabel tabil2;
    private javax.swing.JLabel win;
    private javax.swing.JLabel wrong1;
    private javax.swing.JLabel wrong2;
    private javax.swing.JLabel wrong3;
    private javax.swing.JLabel wrong4;
    private javax.swing.JLabel wrong5;
    // End of variables declaration//GEN-END:variables
}
